spring:
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

app:
  rabbitmq:
    exchange: ${APP_RABBITMQ_EXCHANGE:notificacoes.exchange}

jwt:
  secret: ${JWT_SECRET}
  validity: ${JWT_VALIDITY}
google:
  client:
    id: ${GOOGLE_CLIENT_ID}